### ISSUE TITLE
F-Driod build failed

### ISSUE THREAD

**Issue by linsui** [jheubuch/traewelling-android#412] opened 2024-08-18 09:53 UTC
**Describe the bug**
https://github.com/Traewelldroid/traewelldroid/pull/409 added an aar to the repo which is not allowed by F-Droid. Why is a local aar required? https://gitlab.com/fdroid/fdroiddata/-/jobs/7604814878

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jheubuch** [comment] 2024-08-18 17:32
The local aar is required because I use a library which was only hosted on jcenter (and i didnt had that on my mind until it was shut down). Since this is no longer accessible, I added it shorthand to the repo until I found a solution for replacing it.

**Comment by linsui** [comment] 2024-08-19 06:04
Maybe you can use https://www.jitpack.io/#jcloquell/android-secure-storage/0.1.3?

**Comment by jheubuch** [comment] 2024-08-19 07:07
Sounds like a great idea!

**Comment by jheubuch** [comment] 2024-08-19 07:50
Thanks @linsui for the notice and the help with the library! :)

**Comment by linsui** [comment] 2024-08-19 08:24
Thanks!

**Comment by licaon-kter** [comment] 2024-10-07 08:11
can we reopen?

ref: https://monitor.f-droid.org/builds/log/de.hbch.traewelling/169#site-footer

so I remove those lines and...
```
==== detail begin ====
verification of APK with copied signature failed
Comparing reference APK to APK with copied signature...
Unexpected diff output:
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/assets/dexopt/baseline.prof and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/assets/dexopt/baseline.prof differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/classes.dex and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/classes.dex differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/classes2.dex and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/classes2.dex differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/classes3.dex and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/classes3.dex differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/classes4.dex and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/classes4.dex differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/res/-1.xml and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/res/-1.xml differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/res/21.xml and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/res/21.xml differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/res/2F.xml and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/res/2F.xml differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/res/2n.xml and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/res/2n.xml differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/res/2w1.xml and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/res/2w1.xml differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/res/4H.xml and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/res/4H.xml differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/res/7R.xml and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/res/7R.xml differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/res/7s.xml and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/res/7s.xml differ
Binary files /tmp/tmpx5m_670v/unsigned_binaries_de.hbch.traewelling_169.binary/content/res/B6.xml and /tmp/tmpx5m_670v/_tmp_tmpx5m_670v_sigcp_de.hbch.traewelling_169/content/res/B6.xml differ
...
```

@jheubuch was the foss apk built from the right flavor?

**Comment by jheubuch** [comment] 2024-10-07 08:18
Uhm yes, I think so.. I ran my build script as I run it every time. 🤔

**Comment by jheubuch** [comment] 2024-10-07 08:21
Maybe there was some problem with the `gradle clean` since I first build the Google Play variant and then the FOSS one. For the moment I would draft a new release with a manually rebuilt FOSS release and see if it is fixed...

**Comment by jheubuch** [comment] 2024-10-08 09:26
I created a new release and hope that it is fixed.. somehow

**Comment by licaon-kter** [comment] 2024-10-08 09:50
nope :( https://gitlab.com/fdroid/fdroiddata/-/jobs/8020118520#L1900

/LE: might be related to https://gitlab.com/fdroid/fdroid-suss/-/issues/16 retesting now

**Comment by licaon-kter** [comment] 2024-10-08 10:28
yup confirmed, thanks: https://gitlab.com/fdroid/fdroiddata/-/jobs/8020652015#L383

/close this

**Comment by jheubuch** [comment] 2024-10-08 10:34
ah I see, good to know, thanks for the information :)

**Closed as completed by jheubuch** 2024-10-08 10:34 UTC
Labels: bug
