### ISSUE TITLE
UI/UX issues and improvements

### ISSUE THREAD

**Issue by timoschwarzer** [jheubuch/traewelling-android#125] opened 2023-03-08 11:07 UTC
Just a small list of UI/UX issues and improvement opportunities I encountered while using the app.

- [x] Issues when using the app with larger display scaling factors:
  - [x] The view that displays a ride has overlapping text when usernames are a bit longer
    <img src="https://user-images.githubusercontent.com/8849554/223694253-8e3de1fe-3dd4-42fd-b9b2-b2e73c662cf9.png" width=250>
    I propose making this area scrollable to account for this:
    <img src="https://user-images.githubusercontent.com/8849554/223695480-0a76c156-1af5-4ff5-8c7e-fe00889b57b8.png" width=250>
  - [x] The "Select destination" view items don't expand vertically when the station names are too long, making it hard to read
    <img src="https://user-images.githubusercontent.com/8849554/223695856-d56ac251-7d7d-4727-a40b-871330c7e038.png" width=250>
  - [x] The "Search connection" items layout gets funky when station and/or line names are longer
    <img src="https://user-images.githubusercontent.com/8849554/223696423-5672ffc6-e41d-448e-a69e-b8638fc16fee.png" width=250>
  - [x] The "Select destination" and "Search connection" views should close when pressing "Home" (or the previously selected main tab) again
  - [x] The "Locate" button should give some feedback when pressing, such as a loading indicator on the button for the duration of the location search
  - [x] The app should stop trying to locate the user when focusing the "Stop / Ril100" text box after pressing "Locate" and not override user inputs that happened after pressing "Locate"

Device: Pixel 4a, Android 13
Font size: 3 out of 4
Display size: 4 out of 4

I really love this app, keep up the good work! :heart:

**Comment by jheubuch** [comment] 2023-07-05 09:47
Last open point is duplicate of #107

**Closed as completed by jheubuch** 2023-07-05 09:47 UTC
Labels: bug, approved
