### ISSUE TITLE
Login with Träwelling button does nothing

### ISSUE THREAD

**Issue by cuteredpwnda** [jheubuch/traewelling-android#280] opened 2023-10-28 11:55 UTC
**Describe the bug**
When I start the app for the first time and try to log in, the app closes to the home screen. 

**To Reproduce**
1. Start the app for the first time 
2. Click on 'Log in with Träwelling' button

**Expected behavior**
The browser to open, showing the login mask or a prompt, that the login was successful

**Screenshots**
![The apps start-up screen ](https://github.com/Traewelldroid/traewelldroid/assets/18485146/f4449040-9b77-43e1-92c5-1850c5b22a68)

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord 7
 - OS: Android 12, latest patch
 - Browser: Firefox
 - Version: 119.0 (Build #2015980915)

**Comment by jheubuch** [comment] 2023-10-29 12:15
Hi, are you using Firefox?
I think this could be a duplicate of #250

**Comment by cuteredpwnda** [comment] 2023-10-30 07:15
Yes, you are right, sorry, did not use the right words to search for this existing issue!

**Closed as not planned** 2023-10-30 07:51 UTC
Labels: bug
