### ISSUE TITLE
Login with Träwelling impossible with disabled Chrome

### ISSUE THREAD

**Issue by MrGamy** [jheubuch/traewelling-android#250] opened 2023-09-03 10:50 UTC
**Describe the bug**
Disabling Chrome on Android breaks "Login with Träwelling". Instead of a browser opening, you get send to desktop without any error message.

**To Reproduce**
1. Reset Träwelldroid by deleting app data
2. Download a custom Browser (e.g. Firefox)
3. Disable Chrome
4. Set the new Browser as default Browser 
5. Open Träwelldroid and try to "Login with Träwelling"

**Expected behavior**
The default browser opens the required login page

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 13
 - Browser: Firefox
 - Version: 117.0 (Build #2015969571)

**Comment by jheubuch** [comment] 2023-09-03 11:48
duplicate of #249

**Comment by jheubuch** [comment] 2023-09-03 11:48
duplicate of #249

**Closed as not planned by jheubuch** 2023-09-03 11:48 UTC
Labels: bug
