### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by rugk** [jheubuch/traewelling-android#36] opened 2022-05-04 09:41 UTC
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

BTW a release on F-Droid could also bring some (more) popularity (in case that is intended), as it will show up in the app (new apps are featured there).

**Comment by jheubuch** [comment] 2022-05-04 10:52
As this app is not released in public, it isn't planned to release this to F-Droid at the moment.
In future (whenever this will be) I also want to publish Träwelldroid to F-Droid.

**Comment by IzzySoft** [comment] 2022-10-18 14:00
Has the future arrived yet? I see the app now is in the public (you've published it on Google Play), [Exodus states](https://reports.exodus-privacy.eu.org/de/reports/303247/) it's free of trackers – so it looks good! If you could make the signed APK available here in the repo (ideally attached to its release), I could immediately make it available via my repo. Apart from that I'd of course recommend bringing it to F-Droid.org :smiley:

**Comment by DRSchlaubi** [comment] 2022-10-18 15:47
We use Googles OSS license screen which currently blocks it from F-Droid iirc https://github.com/Traewelldroid/traewelldroid/blob/dev/app/build.gradle#L104

**Comment by IzzySoft** [comment] 2022-10-18 16:10
Ah, I see. Some [hints here](https://gitlab.com/-/snippets/1896503#license-dialogs) if you're looking for an alternative (and yes, this is a common issue: the "OSS" in the name off that license is quite misleading, suggesting the library itself would be F/LOSS while it only means it can detect/show OSS licenses without being libre itself)…

While it's stuck: with [my repo](https://apt.izzysoft.de/fdroid) it would be accepted still and only get the `NonFreeDep` anti-feature. So if you want to have it there for now, all I'd need is the APK – ideally attached to its corresponding release. Once the app made it to F-Droid.org we can decide if I shall still keep it (usually I then remove it after a decent overlap to give people a chance to "move over").

Oh, another plus: it would be the APK signed by you, so cross-updates with the PlayStore one would work, in both directions.

**Comment by IzzySoft** [comment] 2022-12-20 16:53
Any chance, @DRSchlaubi?

**Comment by DRSchlaubi** [comment] 2022-12-20 16:57
I am not responsible for publishing so we need @der_heubi for this.

I would suggest using GH Actions to auto generate releases based on main branch activity including APK files

Cross updates probably won't work as play store uses a different signature (Google Play Signing)

**Comment by IzzySoft** [comment] 2022-12-20 19:24
Thanks! Then let's see if der_heubi can get it flying. As for cross-updates: Are you not using the same signing key? I know there was a change and Google now wants to do the signing themselves, but if I'm not mistaken it still is the developer providing that key. Unless the developer choose to let Google create the key, in which case it's unfortunately lost – which then cannot be helped anymore.

**Comment by DRSchlaubi** [comment] 2022-12-21 05:52
The dev signs the aab and then google signs It again

**Comment by jheubuch** [comment] 2022-12-25 20:47
> Thanks! Then let's see if der_heubi can get it flying. As for cross-updates: Are you not using the same signing key? I know there was a change and Google now wants to do the signing themselves, but if I'm not mistaken it still is the developer providing that key. Unless the developer choose to let Google create the key, in which case it's unfortunately lost – which then cannot be helped anymore.

Hi, y'all. Sorry for the delay in response. At the moment, I'm fully occupied by my master's thesis on which I'm currently working on. That's why I personally don't have the time or energy at the moment for having a mind for new app store's policies, the workflows behind and so on. Also I'd not be happy with someone else hosting Träwelldroid on F-Droid in my name unless I had the time to intensively deal with F-Droid and its rules and policies. I hope I have your understanding that this can't come until I have enough energy left for dealing with F-Droid.
Thank you in advance!

**Comment by IzzySoft** [comment] 2022-12-26 21:38
It's a pity, but I see your point. As for the policies: Your app is F/LOSS (using the AGPL), so as long as there are no proprietary elements in, all F-Droid is asking is that you're not opposed to the listing (due to the license we'd not need to ask, but we still do so to signal a friendly work-together). For my repo I'd just need the APK as I have no build system.

Just leaving this little TL;DR in the hope for a day you find time to re-consider. Until then, all the best for your thesis!

**Comment by IzzySoft** [comment] 2023-01-27 13:18
@jheubuch seeing there's an APK attached to the latest release: does that mean you're OK with me pulling it for my repo?

**Comment by IzzySoft** [comment] 2023-02-21 21:02
OK, I take this as "not being opposed" then :smile:

**Comment by jheubuch** [comment] 2023-11-03 12:23
RFP: https://gitlab.com/fdroid/rfp/-/issues/2572

**Comment by jheubuch** [comment] 2024-03-07 17:39
Since the RFP is now closed and the app should be listed in the next few days, I'm closing this now.
Special thanks to @jugendhacker who did the most of work to get this done! 🤗🥳

**Closed as completed by jheubuch** 2024-03-07 17:39 UTC

**Comment by jugendhacker** [comment] 2024-03-14 13:38
It's in the store now: https://f-droid.org/packages/de.hbch.traewelling/ (thanks to reproducible builds all users should be able to switch to it seamlessly if they want to)
